# Generated by Django 4.1.7 on 2023-03-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhdata',
            name='delay_worktime',
            field=models.FloatField(verbose_name='总误时'),
        ),
        migrations.AlterField(
            model_name='lhdata',
            name='equipment_status',
            field=models.CharField(max_length=64, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='lhdata',
            name='work_cycle',
            field=models.FloatField(verbose_name='当前周期'),
        ),
    ]
