# Generated by Django 4.1.7 on 2023-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_alter_lhdata_delay_worktime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LhWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('work', models.IntegerField(verbose_name='生产中')),
                ('stop', models.IntegerField(verbose_name='停机中')),
                ('plan_stop', models.IntegerField(verbose_name='计划停机')),
                ('test', models.IntegerField(verbose_name='调机中')),
                ('work_proportion', models.FloatField(verbose_name='实时开机率')),
            ],
        ),
    ]
