# Generated by Django 4.1.7 on 2023-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_lhworkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhworkstatus',
            name='other',
            field=models.IntegerField(blank=True, null=True, verbose_name='其他'),
        ),
    ]
