# Generated by Django 4.1.7 on 2023-04-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0004_lhworkstatus_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('sys_status', models.IntegerField(default=0, verbose_name='系统状态')),
                ('work_status', models.IntegerField(default=0, verbose_name='运行状态')),
                ('day_output', models.IntegerField(default=0, verbose_name='当班产量')),
                ('order', models.IntegerField(default=0, verbose_name='工单数')),
                ('error', models.IntegerField(default=0, verbose_name='报警代码')),
                ('work_output', models.IntegerField(default=0, verbose_name='当前产量')),
                ('total_output', models.IntegerField(default=0, verbose_name='总产量')),
            ],
        ),
        migrations.CreateModel(
            name='RobotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('work', models.IntegerField(verbose_name='生产中')),
                ('stop', models.IntegerField(verbose_name='停机中')),
                ('test', models.IntegerField(verbose_name='调机中')),
                ('error', models.IntegerField(verbose_name='报警中')),
                ('work_proportion', models.FloatField(verbose_name='实时开机率')),
                ('error_proportion', models.FloatField(verbose_name='实时报警')),
                ('time', models.CharField(max_length=20, unique=True, verbose_name='时间')),
                ('op_everyday', models.IntegerField(default=0, verbose_name='每日总产')),
                ('op_plane', models.IntegerField(default=0, verbose_name='计划产量')),
            ],
        ),
    ]
