# Generated by Django 4.1.7 on 2023-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0005_robotdata_robotstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotdata',
            name='c_speed',
            field=models.FloatField(default=0, verbose_name='C轴设置速度'),
        ),
        migrations.AddField(
            model_name='robotdata',
            name='r_speed',
            field=models.FloatField(default=0, verbose_name='R轴设置速度'),
        ),
        migrations.AddField(
            model_name='robotdata',
            name='x_speed',
            field=models.FloatField(default=0, verbose_name='X轴设置速度'),
        ),
        migrations.AddField(
            model_name='robotdata',
            name='y_speed',
            field=models.FloatField(default=0, verbose_name='Y轴设置速度'),
        ),
        migrations.AddField(
            model_name='robotdata',
            name='z_speed',
            field=models.FloatField(default=0, verbose_name='Z轴设置速度'),
        ),
    ]
