# Generated by Django 4.1.7 on 2023-04-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0006_robotdata_c_speed_robotdata_r_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotdata',
            name='day_output',
        ),
    ]
