# Generated by Django 4.1.7 on 2023-04-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0007_remove_robotdata_day_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotstatus',
            old_name='error',
            new_name='work_error',
        ),
    ]
