# Generated by Django 4.1.7 on 2023-04-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0008_rename_error_robotstatus_work_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotdata',
            old_name='error',
            new_name='work_error',
        ),
        migrations.RenameField(
            model_name='robotdata',
            old_name='order',
            new_name='work_order',
        ),
    ]
