# Generated by Django 4.1.7 on 2023-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0009_rename_error_robotdata_work_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('sys_status', models.IntegerField(default=0, verbose_name='系统状态')),
                ('work_output', models.IntegerField(default=0, verbose_name='总产量')),
                ('total_output', models.FloatField(default=0, verbose_name='当前节拍')),
            ],
        ),
        migrations.CreateModel(
            name='DgStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='刷新时间')),
                ('work', models.IntegerField(verbose_name='生产中')),
                ('stop', models.IntegerField(verbose_name='停机中')),
                ('time', models.CharField(max_length=20, unique=True, verbose_name='时间')),
                ('op_everyday', models.IntegerField(default=0, verbose_name='每日总产')),
                ('efficiency_avg', models.FloatField(default=0, verbose_name='平均节拍')),
            ],
        ),
    ]
