# Generated by Django 4.1.7 on 2023-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0011_remove_dgdata_work_output_dgdata_efficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgstatus',
            name='time',
        ),
        migrations.AddField(
            model_name='dgstatus',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='设备名称'),
        ),
    ]
