# Generated by Django 4.1.7 on 2023-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0013_dgstatus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgstatus',
            name='time',
        ),
        migrations.AlterField(
            model_name='dgstatus',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='设备名称'),
        ),
    ]
