# Generated by Django 4.1.7 on 2023-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0014_remove_dgstatus_time_alter_dgstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgstatus',
            name='time',
            field=models.CharField(default='2023-04-12', max_length=20, verbose_name='时间'),
        ),
    ]
