# Generated by Django 4.1.7 on 2023-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('contact_person', models.CharField(max_length=16, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=32, verbose_name='供应商名')),
                ('contact_person', models.CharField(max_length=16, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
            ],
        ),
    ]
