# Generated by Django 4.1.7 on 2023-05-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rjd', '0003_alter_privateaccount_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rjd.supplier', to_field='supplier_name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='供应商名'),
        ),
    ]
