# Generated by Django 4.1.7 on 2023-05-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rjd', '0004_alter_publicaccount_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(verbose_name='日期')),
                ('product_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='品名')),
                ('quantity', models.CharField(blank=True, max_length=16, null=True, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已付款')),
                ('final_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='尾款')),
                ('tax', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], verbose_name='含税')),
                ('bill', models.CharField(blank=True, max_length=64, null=True, verbose_name='发票备注')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rjd.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(verbose_name='日期')),
                ('product_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='品名')),
                ('product_model', models.CharField(blank=True, max_length=16, null=True, verbose_name='型号')),
                ('quantity', models.CharField(blank=True, max_length=16, null=True, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已付款')),
                ('final_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='尾款')),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rjd.custominfo')),
            ],
        ),
    ]
