# Generated by Django 4.1.7 on 2023-05-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjd', '0007_alter_accountsreceivable_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaccount',
            name='type',
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='supplier',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='tax',
            field=models.CharField(max_length=16, verbose_name='含税'),
        ),
    ]
