# Generated by Django 4.1.7 on 2023-05-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjd', '0008_remove_publicaccount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateaccount',
            name='supplier',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='unpaid',
            name='supplier',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='unpaid',
            name='tax',
            field=models.CharField(max_length=16, verbose_name='含税'),
        ),
    ]
