# Generated by Django 4.1.7 on 2023-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjd', '0010_alter_privateaccount_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaid',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='刷新时间'),
        ),
        migrations.AlterField(
            model_name='unpaid',
            name='tax',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='含税'),
        ),
    ]
